name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # TODO: add description
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # TODO: add description
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

      # TODO: add description
    - name: Load Maps API Key from secrets
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo MAPS_API_KEY=\"MAPS_API_KEY\" > ./local.properties

      # TODO: add description
#    - name: Create empty google-services.json
#      run: cat /home/runner/work/xpense/xpense/app/google-services.json | base64

      # TODO: add description
    - name: Put env secret in google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
#      run: echo GOOGLE_SERVICES_JSON > /home/runner/work/xpense/xpense/app/google-services.json
      run: echo $GOOGLE_SERVICES_JSON > xpense/app/google-services.json

      # TODO: add description
    - name: Build with Gradle
      run: ./gradlew build
